In [ ]:
# 02_sql_queries.ipynb
# -----------------------
# Step 2: Running SQL Queries

import pandas as pd
import sqlite3

conn = sqlite3.connect("sales.db")

# 1️⃣ Monthly Sales
monthly_sales = pd.read_sql("""
SELECT year, month, SUM(sales) AS monthly_sales
FROM sales
GROUP BY year, month
ORDER BY year, month;
""", conn)
print("Monthly Sales:\n", monthly_sales.head())

# 2️⃣ Top Products
top_products = pd.read_sql("""
SELECT product_name, SUM(sales) AS total_sales, COUNT(*) AS num_orders
FROM sales
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;
""", conn)
print("Top Products:\n", top_products)

# 3️⃣ Top Customers
top_customers = pd.read_sql("""
SELECT customer_name, SUM(sales) AS total_sales, COUNT(*) AS num_orders
FROM sales
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;
""", conn)
print("Top Customers:\n", top_customers)

# 4️⃣ Segment Sales
segment_sales = pd.read_sql("""
SELECT segment, SUM(sales) AS total_sales, AVG(sales) AS avg_sales
FROM sales
GROUP BY segment
ORDER BY total_sales DESC;
""", conn)
print("Segment Sales:\n", segment_sales)

# 5️⃣ Region Sales
region_sales = pd.read_sql("""
SELECT region, SUM(sales) AS total_sales
FROM sales
GROUP BY region
ORDER BY total_sales DESC;
""", conn)
print("Region Sales:\n", region_sales)

# 6️⃣ State Sales
state_sales = pd.read_sql("""
SELECT state, SUM(sales) AS total_sales
FROM sales
GROUP BY state
ORDER BY total_sales DESC;
""", conn)
print("State Sales:\n", state_sales)

# 7️⃣ Ship Mode Sales
shipmode_sales = pd.read_sql("""
SELECT ship_mode, SUM(sales) AS total_sales, COUNT(*) AS num_orders
FROM sales
GROUP BY ship_mode
ORDER BY total_sales DESC;
""", conn)
print("Ship Mode Sales:\n", shipmode_sales)